# Generated by Django 6.0 on 2026-01-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizaa',
            name='image',
            field=models.ImageField(upload_to='Pizaa/'),
        ),
    ]
