# Generated by Django 6.0 on 2026-01-05 04:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_pizaa_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizaa',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
