# Generated by Django 6.0 on 2026-01-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_pizaa_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizaa',
            name='image',
            field=models.ImageField(upload_to='pizza/'),
        ),
    ]
