[build]
  # This tells Netlify how to install your apps and collect images/css
  command = "pip install -r requirements.txt && python manage.py collectstatic --noinput"
  
  # This is where your CSS/JS files will be saved for Netlify to serve
  publish = "staticfiles"

[functions]
  # This tells Netlify where your "bridge" code is located
  directory = "netlify/functions"

[[redirects]]
  # This sends all web traffic (orders, logins, etc.) to your Django code
  from = "/*"
  to = "/.netlify/functions/django_server"
  status = 200